lab23/CookBook/Models/Author.cs
using System.Collections.Generic;

namespace CookBook.Models
{
    public class Author
    {
        // ID автора
        public int Id { get; set; }
        // имя автора
        public string AuthorName { get; set; }
        // список рецептов автора
        public List<Recipe> RecipesList { set; get; }
    }
}

lab23/CookBook/Models/BookContext.cs
using System.Data.Entity;

namespace CookBook.Models
{
    public class BookContext : DbContext
    {
        public DbSet<Recipe> Recipes { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Author> Authors { get; set; }
    }
}

lab23/CookBook/Models/Category.cs
using System.Collections.Generic;

namespace CookBook.Models
{
    public class Category
    {
        // ID категории
        public int Id { get; set; }
        // название категории
        public string Name { get; set; }
        // описание категории
        public string Desc { get; set; }
        // список рецептов из категории
        public List<Recipe> RecipesList { set; get; }
    }
}

lab23/CookBook/Models/Recipe.cs
using System;

namespace CookBook.Models
{
    public class Recipe
    {
        // ID рецепта
        public int Id { get; set; }
        // название рецепта
        public string Title { get; set; }
        // автор рецепта
        public string Author { set; get; }
        // аннотация к рецепту
        public string RecipeDesc { get; set; }
        // изображение
        public string Img { get; set; }
        // текст рецепта
        public string Content { get; set; }
        // категория
        public virtual Category Category { set; get; }
        // дата загрузки
        public DateTime Date { get; set; }
    }
}

lab23/CookBook/Controllers/DBController.cs
using CookBook.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CookBook.Controllers
{
    public class DBController : Controller
    {
        BookContext db = new BookContext();
   
        public ActionResult Index()
        {
            return View();
        }
        // Создание новой записи
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Recipe recipe)
        {
            //if (recipe.Img != null)
            //{
            //    byte[] imageData = null;
            //    // считываем переданный файл в массив байтов
            //    using (var binaryReader = new BinaryReader(recipe.Img.OpenReadStream()))
            //    {
            //        imageData = binaryReader.ReadBytes((int)recipe.Img.Length);
            //    }
            //    // установка массива байтов
            //    recipe.Img = imageData;
            //}
            recipe.Date = DateTime.Now;
            db.Recipes.Add(recipe);
            db.SaveChanges();

            return Redirect("/Home/Index");
        }
        // Удаление записи
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipes = db.Recipes.Find(id);
            if (recipes == null)
            {
                return HttpNotFound();
            }
            db.Recipes.Remove(recipes);
            db.SaveChanges();
            return Redirect("/Home/Index");
        }
        //Изменение записи
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe != null)
            {
                return View(recipe);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult Edit(Recipe recipe)
        {
            recipe.Date = DateTime.Now;
            db.Entry(recipe).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect("/Home/Index");
        }
    }
}

lab23/CookBook/Controllers/HomeController.cs
using CookBook.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CookBook.Controllers
{
    public class HomeController : Controller
    {
        // создаем контекст данных
        BookContext db = new BookContext();

        public ActionResult Index()
        {
            return View(db.Recipes);
        }

        public ActionResult Show(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        [HttpPost]
        public ActionResult RecipeSearch(string name)
        {
            var allrecipes = db.Recipes.Where(a => a.Author.Contains(name)).ToList();
            if (allrecipes.Count > 0)
            {
                return PartialView(allrecipes);
            }
            else
            {
                return Redirect("Index");
            }
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult WebApi()
        {
            return View();
        }


        // закроем бд
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

lab23/CookBook/Controllers/RecipeApiController.cs
using CookBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
//using System.Web.Mvc;


namespace CookBook.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class RecipeApiController : ControllerBase
    {
        BookContext db = new BookContext();
        
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Recipe>>> Get()
        {
            return await db.Recipes.ToListAsync();
        }

        // GET api/users/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Recipe>> Get(int id)
        {
            Recipe recipe = await db.Recipes.FirstOrDefaultAsync(x => x.Id == id);
            if (recipe == null)
                return NotFound();
            return new ObjectResult(recipe);
        }

        [HttpPost]
        public async Task<ActionResult<Recipe>> Post(Recipe recipe)
        {
            
            // если есть лшибки - возвращаем ошибку 400
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            // если ошибок нет, сохраняем в базу данных
            db.Recipes.Add(recipe);
            await db.SaveChangesAsync();
            return Ok(recipe);
        }

        // PUT api/users/
        [HttpPut]
        public async Task<ActionResult<Recipe>> Put(Recipe recipe)
        {
            if (recipe == null)
            {
                return BadRequest();
            }
            if (!db.Recipes.Any(x => x.Id == recipe.Id))
            {
                return NotFound();
            }

            recipe.Date = DateTime.Now;
            db.Entry(recipe).State = (System.Data.Entity.EntityState)EntityState.Modified;
            db.SaveChanges();
            await db.SaveChangesAsync();
            return Ok(recipe);
        }

        // DELETE api/users/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Recipe>> Delete(int id)
        {
            Recipe recipe = db.Recipes.FirstOrDefault(x => x.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }
            db.Recipes.Remove(recipe);
            await db.SaveChangesAsync();
            return Ok(recipe);
        }
    }
}

lab23/CookBook/Views/DB/Create.cshtml
@{
    ViewBag.Title = "Добавление нового рецепта";
}

@model CookBook.Models.Recipe

<h2>Новый рецепт</h2>

<div>
    <form method="post" action="/DB/Create" enctype="multipart/form-data">
        <p>
            Название рецепта:
            <input type="text" name="Title" size="15" maxlength="30" />
        </p>
        <p>
            Автор:
            <input type="text" name="Author" size="15" maxlength="30" />
        </p>
        <p>Краткое описание рецепта: </p>
        <textarea name="RecipeDesc" cols="100" rows="4">Введите текст...</textarea>
        <p>Описание рецепта: </p>
        <textarea name="Content" cols="100" rows="20">Введите текст...</textarea>
        @*<p>Загрузить изображение: </p>
        <input type="file" name="Img" /><br />*@

        <p><input type="submit" value="Отправить" /></p>
    </form>
    </div>

lab23/CookBook/Views/DB/Delete.cshtml
@model CookBook.Models.Recipe
<h2>Удаление рецепта</h2>
<dl>
    <dt>Название</dt>
    <dd>
        @Html.DisplayFor(model => model.Title)
    </dd>

    <dt>Автор</dt>
    <dd>
        @Html.DisplayFor(model => model.Author)
    </dd>

    <dt>Описание рецепта</dt>
    <dd>
        @Html.DisplayFor(model => model.RecipeDesc)
    </dd>
</dl>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

lab23/CookBook/Views/DB/Edit.cshtml
@{
    ViewBag.Title = "Редактировать рецепт";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model CookBook.Models.Recipe

@using (Html.BeginForm("Edit", "DB", FormMethod.Post))
{
<fieldset style="background: #efd0aa">
    @Html.HiddenFor(m => m.Id)
    <p>
        @Html.LabelFor(m => m.Title, "Название рецепта")
        <br />
        @Html.EditorFor(m => m.Title)
    </p>
    <p>
        @Html.LabelFor(m => m.Author, "Автор")
        <br />
        @Html.EditorFor(m => m.Author)

    </p>
    <p>
        @Html.LabelFor(m => m.RecipeDesc, "Описание")
        <br />
        @Html.TextAreaFor(m => m.RecipeDesc)
    </p>
    <p>
        @Html.LabelFor(m => m.Content, "Описание")
        <br />
        @Html.TextAreaFor(m => m.Content)
    </p>
    <p><input type="submit" value="Отправить" /></p>
</fieldset>
}

lab23/CookBook/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

lab23/CookBook/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

lab23/CookBook/Views/Home/Index.cshtml
@model IEnumerable<CookBook.Models.Recipe>
<h4>Поиск рецептов по автору:</h4>
<div>
    @using (Ajax.BeginForm("RecipeSearch", new AjaxOptions { UpdateTargetId = "results" }))
    {
        <input type="text" name="name" />
        <input type="submit" value="Поиск" />
    }
    <div id="results"></div>
</div>
<hr />
<h3>Все Рецепты</h3>
<div class="row mt-2 mb-2">
    @{
        foreach (var recipe in Model)
        {
            <div class="col-lg-" style="background: #efd0aa; padding: 5px 5px 5px 5px; margin: 1px 1px 1px 1px;">

                <img class="img-thumbnail" src="@recipe.Img" alt="@recipe.Title" name="@recipe.Title" width="300" />
                <h2>@recipe.Title</h2>
                <p>@recipe.Author</p>
                <p>@recipe.RecipeDesc</p>
                <p><a class="btn-warning" href="/Home/Show/@recipe.Id">Подробнее</a></p>
            </div>
        }
    }
</div>


@Scripts.Render("~/scripts/jquery-1.10.2.min.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.min.js")

lab23/CookBook/Views/Home/RecipeSearch.cshtml
@model IEnumerable<CookBook.Models.Recipe>


<div id="searchresults">
    <h3>Все рецепты автора : @Model.First().Author</h3>
    @foreach (var recipe in Model)
    {
        <div class="col-lg-" style="background: #efd0aa; padding: 5px 10px 5px 10px; margin: 1px 1px 1px 1px;">

            <img class="img-thumbnail" src="@recipe.Img" alt="@recipe.Title" name="@recipe.Title" width="300" />
            <h2>@recipe.Title</h2>
            <p>@recipe.Author</p>
            <p>@recipe.RecipeDesc</p>
            <p><a class="btn-warning" href="/Home/Show/@recipe.Id">Подробнее</a></p>
        </div>
    }
</div>
@section Footer {
    
}

lab23/CookBook/Views/Home/Show.cshtml
@{
    ViewBag.Title = "Просмотр рецепта";
}

@model CookBook.Models.Recipe
<div style="        background: #efd0aa; padding: 5px 10px 5px 10px;">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Title" width="300" />
    <h2>@Html.DisplayFor(m => m.Title)</h2>
    <h4>@Html.DisplayFor(m => m.Author)</h4>
    <p>@Html.DisplayFor(m => m.RecipeDesc)</p>
    <h3>Порядок приготовления:</h3>
    <p>@Html.DisplayFor(m => m.Content)</p>
    <br /><br />
    <h6>Последнее обновление:</h6>
    <h6>@Html.DisplayFor(m => m.Date)</h6>
    <td><p><a class="btn-warning" href="/DB/Delete/@Model.Id">Удалить</a></p></td>
    <td><p><a class="btn-warning" href="/DB/Edit/@Model.Id">Изменить</a></p></td>
</div>

lab23/CookBook/Views/Home/WebApi.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Список пользователей</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <h2>Список рецептов</h2>
    <div id="errors" class="alert alert-danger" style="display:none;"></div>
    <form name="userForm">
        <input type="hidden" name="id" value="0" />
        <div class="form-group col-md-5">
            <label for="title">Имя:</label>
            <input class="form-control" name="title" />
        </div>
        <div class="form-group col-md-5">
            <label for="author">Автор:</label>
            <input class="form-control" name="author"/>
        </div>
        <div class="form-group col-md-5">
            <label for="recipedesc">Краткое описание:</label>
            <input class="form-control" name="recipedesc" />
        </div>
        <div class="panel-body">
            <button type="submit" id="submit" class="btn btn-primary">Сохранить</button>
            <a id="reset" class="btn btn-primary">Сбросить</a>
        </div>
    </form>
    <table class="table table-condensed table-striped  col-md-6">
        <thead><tr><th>Id</th><th>Название</th><th>Автор</th><th>Описание</th><th></th></tr></thead>
        <tbody>
        </tbody>
    </table>
</body>
</html>

lab23/CookBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/Site.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="~/Home/Index">CookBook</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="~/Home/Index">Главная <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/DB/Create">Добавить</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Home/Contact">Контакты</a>
                </li>
            </ul>
            @*<form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>*@
        </div>
    </nav>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <br /> <br />
           <footer class="container">
               @if (IsSectionDefined("Footer"))
               {
                   @RenderSection("Footer")
               }
               else
               {                   
                       <p class="float-right"><a href="#">Back to top</a></p>
                       <p>© 2017-2020 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
               }
           </footer>
       
        @*общая библиотека jQuery*@
        @Scripts.Render("~/scripts/jquery-3.4.1.js")
        @*подключает к приложению функциональность Ajax-хелперов*@
        @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")

    </body>
</html>

lab23/CookBook/Views/Shared/allRecipes.cshtml
@model CookBook.Models.Recipe

<div class="col-lg-4">
    @*<img class="img-thumbnail" src="@Model.img" alt="@Model.name" />*@
    <h2>@Model.Title</h2>
    <p>@Model.Author</p>
    <p>@Model.RecipeDesc</p>
    <p><a class="btn-warning" href="/Home/Show">Подробнее</a></p>
</div>